import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer"; // <-- import your footer here

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Family Fashion Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="pb-0 font-sans"> {/* optional font */}
        <Navbar />
        <main className="min-h-[calc(100vh-80px)]">{children}</main> {/* ensures footer sticks below content */}
        <Footer /> {/* <-- footer placed here */}
      </body>
    </html>
  );
}